proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options SAMEORIGIN always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy 'strict-origin';
proxy_cookie_path ~(.*) "$1; SameSite=strict; secure; httponly";


# add_header Feature-Policy "geolocation 'self'; camera 'self';";
# add_header Permissions-Policy "geolocation 'self'; camera 'self'; speaker 'none';";
# add_header Content-Security-Policy: "default-src 'self' blob: data: videochatapp.pl; script-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net https://maps.googleapis.com https://storage.googleapis.com; object-src 'self' videochatapp.pl; img-src * 'self' blob: data: https: videochatapp.pl image.flaticon.com https://videochatapp.pl; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net";
# add_header X-Content-Security-Policy: "default-src 'self' blob: data: videochatapp.pl; script-src 'self'  https://fonts.gstatic.com https://cdn.jsdelivr.net ; object-src 'self' videochatapp.pl; img-src videochatapp.pl image.flaticon.com https://videochatapp.pl; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net";
# add_header X-WebKit-CSP: "default-src 'self' blob: data: videochatapp.pl; script-src 'self'  https://fonts.gstatic.com https://cdn.jsdelivr.net; object-src 'self' videochatapp.pl; img-src videochatapp.pl image.flaticon.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net";
proxy_no_cache 1;
proxy_cache_bypass 1;
